### ISSUE TITLE
Use database/store to track recognised users

### ISSUE THREAD

**Issue by DanielOaks** [KnightHawk3/Rhythm#5]
We should be able to track recognised users between reboots as the old motionbot does. The original data store uses MongoDB with an existing format for storing recognised users. If possible, it'd be nice to incorporate with this and use the existing system, though I've never played much with MongoDB.

If all else fails, we can look into an alternative store.

**Comment by KnightHawk3** [comment]
MongoDB is nice, I hate databases though and if it were left to me I would probably just end up having a dictionary pickled to a file.

But if someone wants to implement it, a database is probably better, especially one nice like MongoDB

**Comment by DanielOaks** [comment]
Implemented and merged into master using MongoDB.
